template-repository: jebel-quant/rhiza
include:
    - .devcontainer/
    - .github/
    - presentation/
    - book/
    - tests/
    - .editorconfig
    - .pre-commit-config.yaml
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - README.md
    - LICENSE
    - Makefile
    - ruff.toml
    - pytest.ini
exclude:
    - book/minibook-templates
    - book/pdoc-templates
    - .github/renovate.json
